name: Build macOS Application

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macOS 26

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install dependencies
      run: |
        brew install ffmpeg
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build Application with PyInstaller
      run: |
        # This creates the .app bundle inside the dist/ folder
        pyinstaller -y --onedir --windowed --icon=controls.icns --osx-bundle-identifier=com.setlist-audio-normalizer main.py

    - name: Create DMG (Disk Image)
      run: |
        brew install create-dmg
        create-dmg \
          --volname "SETLISTNORMALIZER" \
          --window-pos 200 120 \
          --window-size 600 400 \
          --icon-size 100 \
          --icon "controls.icns" 200 190 \
          "dist/setlistnormalizer.dmg" \
          "dist/setlistnormalizer.app"

    - name: Upload macOS Application Artifact
      uses: actions/upload-artifact@v4
      with:
        name: setlistnormalizer.dmg
        path: dist/setlistnormalizer.dmg
