Skip to content
Buskyboy
audio-normalize
Repository navigation
Code
Issues
Pull requests
Agents
Actions
Projects
Wiki
Security and quality
Insights
Settings
Files
Go to file
t
T
.github/workflows
mac-build
main.yml
.DS_Store
.gitignore
MEMORIES (2).mp3
ROCKIN AT MIDNIGHT D.mp3
SHES NOT YOU.mp3
TAKE IT EASY (G).mp3
controls.icns
controls.ico
main.py
requirements.txt
shame_raw.mp3
teardrops_raw.mp3
audio-normalize/.github/workflows
/mac-build
Buskyboy
Buskyboy
Create mac-build v1.00
eaab565
 · 
5 minutes ago
audio-normalize/.github/workflows
/mac-build

Code

Blame
39 lines (30 loc) · 892 Bytes
name: Build Windows Executable

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # Allows you to manually trigger the build

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install ffmpeg
      uses: FedericoCarboni/setup-ffmpeg@v3

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

 
    - name: Build Executable with PyInstaller
      run: |
        pyinstaller -y --onefile --windowed --icon=downloading.ico myDownloader.py

    - name: Upload Executable Artifact
      uses: actions/upload-artifact@v4
      with:
        name:set-list-normalizer
        path: dist/setlistorganizer.exe

Explain

